#!/bin/sh
case $1/$2 in
  pre/*)
    echo "Going to $2..."
    killall autorotate.sh
    exit 0
    ;;
  post/*)
    echo "Waking up from $2..."
        killall autorotate.sh
        sleep 3
        su root -c "autorotate.sh > /tmp/autorotate.log 2>&1 &"
    ;;
esac

